    export const Products=[
    {id:0,
    
    question:"From which tag descriptive list starts ?",
    correct:"LL",
    b:"DD",    
    c:"DS",   
    d:"DS",    
    count:1,
    total:0
},
{id:1,
    
    question:"Correct HTML tag for the largest heading is",
    correct:"head",
    b:"h6",    
    c:"heading",   
    d:"h1", 
    count:1,
    total:0
},
{id:2,
    
    question:"What is the correct sequence of HTML tags for starting a webpage?",
    a:"Head, Title, HTML",
    b:"Title, Head, HTML",    
    correct:" HTML, Head, Title",   
    d:"Bold",   
     count:1,
    total:0
},
{id:3,
    
    question:"What is the correct HTML tag for inserting a line break?",
    correct:"Br",
    b:"Break",    
    c:"Lb",   
    d:"<a/>",    count:1,
    total:0
},
{id:4,
    
    question:"The attribute of <form> tag",
    correct:"Method",
    b:"Action",    
    c:"Both A nad B",   
    d:"Bold",    
    count:1,
    total:0
},
{id:5,
    
    question:"Choose the correct HTML tag to make text bold?",
    correct:"Bold",
    b:"B",    
    c:"Bld",   
    d:"Italic",    count:1,
    total:0
},
// {id:7,
//     img:process.env.PUBLIC_URL + '/glass.jpeg',
//     title:"Sun Glasses Oculoss Retroo male",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// },{id:8,
//     img:process.env.PUBLIC_URL + '/watch.jpeg',
//     title:"Smart Watch Android And Ios",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:1,
//     total:0
// },
// {id:9,
//     img:process.env.PUBLIC_URL + '/mob1.jpeg',
//     title:"google pixel",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:1,
//     total:0
// },
// {id:10,
//     img:process.env.PUBLIC_URL + '/glass.jpeg',
//     title:"Sun Glasses Oculoss Retroo male",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// },
// {id:11,
//     img:process.env.PUBLIC_URL + '/iphoneconvert.jpeg',
//     title:"iPhone XR Convert To iPhone 11",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// },
// {id:12,
//     title:"samsumg",
//     img:process.env.PUBLIC_URL + '/mob1.jpeg',
//     price:10,
//     company:"verizone",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// },
// {id:13,
//     img:process.env.PUBLIC_URL + '/cycleglass.jpeg',
//     title:"Cycling Sunglasses Riding Bluetooth Earphone",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// },
// {id:14,
//     img:process.env.PUBLIC_URL + '/watch.jpeg',
//     title:"Smart Watch Android And Ios",
//     price:10,
//     company:"google",
//     info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
//     incart:false,
//     count:0,
//     total:0
// }
]



export const Detail=
{id:0,
    img:process.env.PUBLIC_URL + '/null.jpeg',
    title:"Kitchen Sink Faucet Sprayer Water",
    price:10,
    company:"google",
    info:"Click the link above to open an online editor. Feel free to make some changes, and see how they affect the output. Most pages in this guide will have editable examples like this one",
    incart:false,
    count:0,
    total:0
}
